
name: 'Deploy'

on:
  pull_request_target:
    branches: [ "main" ]
    types:
      - closed

permissions:
  contents: read

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    name: 'Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: auth gcp
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        cleanup_credentials: false

    - name: tf setup
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
    - name: tf init
      run: terraform init

    - name: tf format
      run: terraform fmt -check

    # - name: tf plan
    #   run: terraform plan -input=false

    # - name: tf apply
    #   run: terraform apply -auto-approve -input=false
