
name: 'Publish'

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:
    inputs:
      git_ref:
        description: git ref (tag, commit hash, branch) do you want to reset the PUBLIC branch? [default=origin/main]
        type: string
        default: origin/main
        required: true
      git_tag:
        description: what new version tag would you like to create? latest version
        type: string
        default: ${{ github.event.inputs.git_tag || steps.get-latest-tag.outputs.latest_tag }}
        #default: v2.0.19
        required: true

permissions:
  contents: read

jobs:
  publish:
    name: 'publish'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Latest Tag
      id: get-latest-tag
      run: |
        latest_tag=$(git describe --abbrev=0 --tags)
        echo "::set-output name=latest_tag::$latest_tag"

    - name: test
      id: test-id
      run: |
        echo "testing"

    # - name: Set environment variables
    #     run: |
    #       echo "GIT_REF=${{ github.event.inputs.git_ref }}" >> $GITHUB_ENV
    #       echo "GIT_TAG=${{ github.event.inputs.git_tag }}" >> $GITHUB_ENV
  
    # - name: Run Publish Script
    #     run: ./scripts/publish.sh $GIT_REF $GIT_TAG
    #     shell: bash

