
name: 'Publish'

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: git ref (tag, commit hash, branch) do you want to reset the PUBLIC branch? [default=origin/main]
        type: string
        default: origin/main
        required: true
      git_tag:
        description: git ref (tag, commit hash, branch) do you want to reset the PUBLIC branch? [default=origin/main]
        type: number
        default: origin/main
        required: true

permissions:
  contents: read

jobs:
  terraform:
    name: 'publish'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set environment variables
        run: |
          echo "GIT_REF=${{ github.event.inputs.git_ref }}" >> $GITHUB_ENV
          echo "GIT_TAG=${{ github.event.inputs.git_tag }}" >> $GITHUB_ENV
  
    - name: Run Publish Script
        run: ./.github/scripts/publish.sh $GIT_REF $GIT_TAG
        shell: bash

